select @@version;
select db_name();
sp_help RC_PL_31_REP;
sp_spaceused BSKVO_DBF;
sp_helpindex RT_INDEX_DBF;
sp_helprotect TRN_HDR_DBF;
sp_helpdb;
setuser 'guest';

select name from sysobjects where name like '%VRS%'; --H399634_H1S
select * from sysusers where uid=2;
select object_id('TRN_HDR_DBF');

-- RDB scope SQL
select * from RDB_OBJECT_DBF where M_OBJECT_ID='CM.476';
select * from RDB_CLASS_DBF where M_CLASS_NAME=(select M_CLASS_NAME from RDB_OBJECT_DBF where M_OBJECT_ID='CM.476');
select M_RFG_TABLE_NAME,M_RFG_FORMULA,M_RFD_TABLE_NAME,M_RFD_FORMULA from RDBCNSTR_DBF where M_RFG_TABLE_NAME='NPD_BDY_DBF'; and M_RFD_FORMULA='M_INSGEN%';
select M_RFG_TABLE_NAME,M_RFG_FORMULA,M_RFG_RELATIONSHIP,M_RFD_TABLE_NAME,M_RFD_FORMULA,M_RFD_RELATIONSHIP from RDBCNSTR_DBF where M_RFG_TABLE_NAME='CM_MKTSR_DBF'; and M_RFG_FORMULA='M_LABEL';
select 'select * from '+M_RFG_TABLE_NAME+' where '+M_RFG_FORMULA+' = ''188'' ;' from RDBCNSTR_DBF where M_RFD_TABLE_NAME='CM_MKTSR_DBF'; and M_RFD_FORMULA='M_LABEL';

--3.1 queries
select PATH from MXODR_ASSEMBLY_LOG where GSTATUS = 'F';
select M_TRN_FMLY,M_TRN_GRP, M_TRN_TYPE, count(1) from TRN_HDR_DBF T join FLT_MAP_DBF M on T.M_NB = M.M_NB group by M_TRN_FMLY,M_TRN_GRP, M_TRN_TYPE order by count(1) DESC; --what s the representation of the deals in FLT_MAP_DBF?

select dyn.M_IDJOB,dyn.M_DATEGEN,scn.M_REFERENCE, scn.M_NB_ITEMS,case when dyn.M_EXE_STATUS = 'T' then 'On-going' when dyn.M_EXE_STATUS = 'F' then 'Failed' end as STATUS, count(*) as REMAINING, ((scn.M_NB_ITEMS - count(*))/scn.M_NB_ITEMS) * 100 as PCT_COMPLETE
from DYN_AUDIT_REP dyn join SCANNER_REP scn on convert(char,dyn.M_IDJOB) = scn.M_EXT_ID
    join BATCH_REP bat on scn.M_REFERENCE = bat.M_SCANNER_ID
    join ITEM_REP itm on itm.M_BAT_REF= bat.M_BAT_REF and itm.M_SCANNER_ID = bat.M_SCANNER_ID
group by dyn.M_IDJOB,scn.M_REFERENCE order by dyn.M_IDJOB;-- Remaining deals to be completed per batch of feeders

select dyn.M_IDJOB,dyn.M_DATEGEN,scn.M_REFERENCE, itm.M_ITM_REF
from DYN_AUDIT_REP dyn join SCANNER_REP scn on convert(char,dyn.M_IDJOB) = scn.M_EXT_ID
    join BATCH_REP bat on scn.M_REFERENCE = bat.M_SCANNER_ID
    join ITEM_REP itm on itm.M_BAT_REF= bat.M_BAT_REF and itm.M_SCANNER_ID = bat.M_SCANNER_ID
where dyn.M_IDJOB = 1306763; -- list of remaining deals to be completed per batch of feeders

select M_IDJOB, M_DATEGEN, M_DELETED, M_TAG_DATA from DYN_AUDIT_REP where M_DELETED='N' and M_TAG_DATA='CPLIRD'; -- get information about the audit of batch of feeders execution

select count(1) from RC_PL_31_REP where M_TRN_FMLY='CURR' and M_MX_REF_JOB=237777 and M_NBZ>0;
select M_NB,M_CONTRACT from TRN_HDR_DBF where M_NB in (6764800, 6743362);
select * from RC_PL_31_REP where M_NBZ = 6743362;

--2.11 queries
select * from TRN_USRD_DBF where M_LABEL like '%REALTIME%';
select T1.M_GROUP, T1.M_USER, T2.M_E_UP, T2.M_DESC from TRN_USRG_DBF T1 join TRN_USRD_DBF T2 on T1.M_USER = T2.M_LABEL where T1.M_GROUP like '%FO%' order by T1.M_GROUP, T1.M_USER ;
select count(*) from COREPL2_REP where M_MX_REF_JOB = 1306746;
select * from DYN_AUDIT_REP where M_OUTPUTTBL='COREPL2.REP';
select * from TRN_HDR_DBF where TRN_HDR_DBF.M_NB = 6743362;
select * from RC_PL_211_REP where M_NB = 6743362;

-- BBVA rec scope of deals
truncate table MX_USER_GROUP_DBF;
select max(M_ID) from TRN_ARCH_DBF;
select * from DPI_ID_DBF where M_LABEL1 = 'SPB_ARC' and M_LABEL2 = 'trn_arch.dbf'; -- 59
select count(1) as Num from TRN_HDR_DBF where M_NB in (select M_NB from RT_LOAN_DBF where M_FLEX=1) and M_TRN_STATUS<>'DEAD';

insert TRN_ARCH_DBF(M_ID,M_TIME_CMP,M_BO_FO,M_USR_NAME,M_USR_GROUP,M_USR_DESK,M_DELETED,M_PC,M_COMMENT,M_DATE_ARC)
values (61,60000,'BO','REALTIME','HOUSEKEEP','',0,0,'Manual purge of deals for the ROF','2015/10/21');
select * from TRN_ARCH_DBF;

drop table BBVA_FLT_MAP_FULLCORE_DBF;
select T1.M_NB into BBVA_FLT_MAP_FULLCORE_DBF from TRN_HDR_DBF T1 join FLT_MAP_FULLCORE_DBF T2 on T1.M_NB=T2.M_NB
where T1.M_BPFOLIO in 
('AAAPDFX1','AAAPDFX2','AAAPDFX3','AAAPDG01','AAAPDG02','AAAPDG04','AAAPDRV1','AAAPDRV2','AAAPDRV3',
'AAAPDTI1','AAAPDTI1B','AAAPDTI2','AAAPDTI3','ANALISTAS','ASSET MILAN','ASSETBONOS','ASSWMIL',
'ASWGOB','BANKING_BOOK','BBV BERMUDA COR','BBV CORTO','BBV CORTO MCO2','BBV DIG','BBV VANILLA',
'BBV VANILLAMC02','BB_ASIA','BCAT TIPOS LARG','BCAT VOL INT','BDT BBV MC02','BDT CORTO MC02',
'BDTBBV2','BDTBBV3','BERM USD COR','BERMUDA DOM','BERMUDA EUROESB','BNACOBLAR','BNACOBVOL','BOND OPT'
,'BOND_INFLATION','BONOS FORWARD','BONOS_LINKERS','CDS_LARGO_PLAZO','CFCHIPOT','CHILENOS',
'CHILENOS BBVA','CL LARGO','CL VOLAT TIPOS','CLOSE BDT BBV','CLOSE BDT MC02','COBERPAT','COBEXTEXO',
'COBMAXMIN','COB_BONOS','COB_EXTERNAL','COB_EXT_TIPOS','CORPOIRS','CORRELACION USD','CORTO NO BDT',
'CORTOPLAZO','CORTO_PLAZO_CLI','CPCDIFWBO','CPCDIOTC','CPCGARENT','CPCVENCOR','CPMDENREG','CPMDERIVA',
'CPMDERMN','CPMDIIRS','CPMDIOTC','CPMSPREMX','CPPI_SWAPS','CRCTASAS','CRDBANCOS','CRDBTBCLP','CRDBTBCOP',
'CRDBTBPEN','CRDCHILE','CRMCHL','CRMPEN','CRMTASAS','CRMTEMPO','CVA_CORTO','CVA_LARGO','CVA_RATES',
'DDIVIRS','DEMESTTC','DEMESTTI','DEMSWAPTI','DEMSWATOT','DEMVOLATI','DEMVOLTOT','DERCOMBI','DIG BBVA',
'DIG DOM','DIG EUROESB','DIGUSDBBVA','ELECTRICAS','ESMCOATRM','ESMDEPOS','ESMDIGTIE','ESMDIGTOT','ESMESTRMI',
'ESMESTRVA','ESMESTTAS','ESMFLEXIC','ESMMMOO','ESMWARRAN','ESP-INFLATION','ESTRATEGIAS','ESTRATFLOW',
'ESTRATGFI','ESTRATGFI_BOND','ETFCORTO','ETFDEUDA','EUR-INFLATION','EUROFIMA','EXOTICAS','FOCSWANEG',
'FOMIRSMNR','FOMMCRO10','FOMMCRO11','FOMMCRO14','FOMMCRO15','FOMMCRO16','FOMMCRO18','FOMMCRO19','FOMMCRO21',
'FOMMCRO22','FOMMCRO25','FOMMCRO29','FOMMICRO2','FOMMICRO4','FOMMICRO5','FOMMICRO8','FOMMICRO9','FOMMIRSNC',
'FOMSWATME','FOMTEMPO','FORWARD','FVA SWAPS','FVA_COLATERAL','FVA_COLAT_BILAT','FVA_COLAT_CCP','FVA_INFLATION',
'FVA_LT_ASIA','FVA_NP_IR','FVA_RATES','FVA_RATES_ASIA','FVA_VOL_RATES','G3','G3_EQUITY','HEDGEAV','HEDGEVIT',
'HIBRIDOS','HIPOTECRED','INDICES DEUDA','INTERNAS_SABR','IRSCOMBI','IRSMEFF','IRSTRAD','IR_CINE','IR_STOCK',
'KOR_LT_SWAP','LARGO NO BDT','LATAM_SWAPS','LIS TIPOS','LON_ESTRUCTURAS','LPMASIGNA','LPMDCCEUR',
'LPMDCCINT','LPMDCCMXN','LPMDCCUSD','LPMDCNCOL','LPMDIDEPO','LPMDIMMOO','LPMDIOTC','LPMDIRBAS','LPMDIRCUR',
'LPMEXDER','LPMIRS1','LPMIRS2','LPMVOLTAS','LPMVOLTOT','LPMXDERSW','LT NY','LT NY2','LT_ASIA','LT_BOND',
'LT_BONDH','LT_BONDT','LT_CNH','LT_HKD','LT_HKFX2','LT_HKFX_CNH','LT_HK_OPT','LT_KOREA','LT_KOREA_REPO',
'LT_KRW','LT_PROGRAM','LT_TWD','MACROBCLSW','MACROBCLVOL','MAD_UST_BTB','MGDSTOXAF','MI ESTRUCTURAS',
'MICROCOB','MKMDERIV','MKMTRDEPO','NON_LIN_HF','NP_COMMODITIES','NP_FOREX','NY_ST_DER','OPCBDTHOJAS',
'OPCION COB','OPCION NC','OPCMIBOR','OPCOTCBON','OPCSALES','OPERPAT','OPTIPCFC','POCXCCY','POMFX',
'POMINVERS','POMIRSTIE','POMUDIMKT','POMUDIS','POMVALREL','POMXCCY','PROFIT','PROJECT_GL_SW','PROJECT_GL_VT',
'PT_CREDITO','PT_FX','PT_RV','PT_SWAPS','REVERFLFL','SLOPE_SABR','STIR_ASIA','STIR_CNH','STIR_EUR',
'STOCKPYME','SWACLIDIV','SWACLIINT','SWAPDIVCO','SWAPDIVNC','SWAPFXIRS','SWAPINTCO','SWAPINTNC',
'SWAPS_CVA','SWAPS_RF','SWAPTION EURO','SWAPTION LARGO','SWAPTION USD','SWAPTIONAV','SWAPTIONUSDBBVA',
'SWBBVA','SWDIRFIN','SWNYBBVA','SW_BANKS','SW_CCY_BASIS','SW_COLAT_PT','SW_CORTO','SW_ELECTRONIC',
'SW_EQUITY','SW_GBP','SW_GERMANY','SW_INSURANCE','SW_PASTORA','SW_TI','SW_TRADING_1','SW_TRADING_2',
'SW_TRADING_3','SW_TRADING_4','SW_TRADING_5','SW_TRADING_6','SW_USD','TAIWAN_FX','TAIWAN_IRS',
'TEMP MC02','TIPDIVCFC','TRD3SPREAD','TWN_LTIRD1_DBU','UNNIM_VTIP','US-INFLATION','UST_BOND','UST_LOCK',
'UST_SPREAD','UST_STRAT','VOL ASSET SWAP','VOL-INFLATION','VOLASIA1','VOLASIA2','VOLASIA3','VOLASIA5',
'VOLASIA6','VOLAUD','VOLCHF','VOLCNY','VOLCNY_EXO','VOLGBP','VOLHKD','VOLHKD_2','VOLJPY','VOLKRW',
'VOLSGD','VOLTWD','VOLUSD','VRMCAPCNF','VRMEXOTIC','VRMEXOTOT','VTABNPVMX','VTACAJAMX','VTC BBVA',
'VTCBDTBBVA','VTCOPCBONOBBVA','VTCSWAPTIONBBVA','VTLBDTBBVA','VTLDIGBBVA','VTLVANILLABBVA','XXBBVLPSW',
'ZZASSETSWAP','ZZMC02','ZZSWAPS','ZZUSA')
or T1.M_SPFOLIO in
('AAAPDFX1','AAAPDFX2','AAAPDFX3','AAAPDG01','AAAPDG02','AAAPDG04','AAAPDRV1','AAAPDRV2','AAAPDRV3',
'AAAPDTI1','AAAPDTI1B','AAAPDTI2','AAAPDTI3','ANALISTAS','ASSET MILAN','ASSETBONOS','ASSWMIL',
'ASWGOB','BANKING_BOOK','BBV BERMUDA COR','BBV CORTO','BBV CORTO MCO2','BBV DIG','BBV VANILLA',
'BBV VANILLAMC02','BB_ASIA','BCAT TIPOS LARG','BCAT VOL INT','BDT BBV MC02','BDT CORTO MC02',
'BDTBBV2','BDTBBV3','BERM USD COR','BERMUDA DOM','BERMUDA EUROESB','BNACOBLAR','BNACOBVOL','BOND OPT'
,'BOND_INFLATION','BONOS FORWARD','BONOS_LINKERS','CDS_LARGO_PLAZO','CFCHIPOT','CHILENOS',
'CHILENOS BBVA','CL LARGO','CL VOLAT TIPOS','CLOSE BDT BBV','CLOSE BDT MC02','COBERPAT','COBEXTEXO',
'COBMAXMIN','COB_BONOS','COB_EXTERNAL','COB_EXT_TIPOS','CORPOIRS','CORRELACION USD','CORTO NO BDT',
'CORTOPLAZO','CORTO_PLAZO_CLI','CPCDIFWBO','CPCDIOTC','CPCGARENT','CPCVENCOR','CPMDENREG','CPMDERIVA',
'CPMDERMN','CPMDIIRS','CPMDIOTC','CPMSPREMX','CPPI_SWAPS','CRCTASAS','CRDBANCOS','CRDBTBCLP','CRDBTBCOP',
'CRDBTBPEN','CRDCHILE','CRMCHL','CRMPEN','CRMTASAS','CRMTEMPO','CVA_CORTO','CVA_LARGO','CVA_RATES',
'DDIVIRS','DEMESTTC','DEMESTTI','DEMSWAPTI','DEMSWATOT','DEMVOLATI','DEMVOLTOT','DERCOMBI','DIG BBVA',
'DIG DOM','DIG EUROESB','DIGUSDBBVA','ELECTRICAS','ESMCOATRM','ESMDEPOS','ESMDIGTIE','ESMDIGTOT','ESMESTRMI',
'ESMESTRVA','ESMESTTAS','ESMFLEXIC','ESMMMOO','ESMWARRAN','ESP-INFLATION','ESTRATEGIAS','ESTRATFLOW',
'ESTRATGFI','ESTRATGFI_BOND','ETFCORTO','ETFDEUDA','EUR-INFLATION','EUROFIMA','EXOTICAS','FOCSWANEG',
'FOMIRSMNR','FOMMCRO10','FOMMCRO11','FOMMCRO14','FOMMCRO15','FOMMCRO16','FOMMCRO18','FOMMCRO19','FOMMCRO21',
'FOMMCRO22','FOMMCRO25','FOMMCRO29','FOMMICRO2','FOMMICRO4','FOMMICRO5','FOMMICRO8','FOMMICRO9','FOMMIRSNC',
'FOMSWATME','FOMTEMPO','FORWARD','FVA SWAPS','FVA_COLATERAL','FVA_COLAT_BILAT','FVA_COLAT_CCP','FVA_INFLATION',
'FVA_LT_ASIA','FVA_NP_IR','FVA_RATES','FVA_RATES_ASIA','FVA_VOL_RATES','G3','G3_EQUITY','HEDGEAV','HEDGEVIT',
'HIBRIDOS','HIPOTECRED','INDICES DEUDA','INTERNAS_SABR','IRSCOMBI','IRSMEFF','IRSTRAD','IR_CINE','IR_STOCK',
'KOR_LT_SWAP','LARGO NO BDT','LATAM_SWAPS','LIS TIPOS','LON_ESTRUCTURAS','LPMASIGNA','LPMDCCEUR',
'LPMDCCINT','LPMDCCMXN','LPMDCCUSD','LPMDCNCOL','LPMDIDEPO','LPMDIMMOO','LPMDIOTC','LPMDIRBAS','LPMDIRCUR',
'LPMEXDER','LPMIRS1','LPMIRS2','LPMVOLTAS','LPMVOLTOT','LPMXDERSW','LT NY','LT NY2','LT_ASIA','LT_BOND',
'LT_BONDH','LT_BONDT','LT_CNH','LT_HKD','LT_HKFX2','LT_HKFX_CNH','LT_HK_OPT','LT_KOREA','LT_KOREA_REPO',
'LT_KRW','LT_PROGRAM','LT_TWD','MACROBCLSW','MACROBCLVOL','MAD_UST_BTB','MGDSTOXAF','MI ESTRUCTURAS',
'MICROCOB','MKMDERIV','MKMTRDEPO','NON_LIN_HF','NP_COMMODITIES','NP_FOREX','NY_ST_DER','OPCBDTHOJAS',
'OPCION COB','OPCION NC','OPCMIBOR','OPCOTCBON','OPCSALES','OPERPAT','OPTIPCFC','POCXCCY','POMFX',
'POMINVERS','POMIRSTIE','POMUDIMKT','POMUDIS','POMVALREL','POMXCCY','PROFIT','PROJECT_GL_SW','PROJECT_GL_VT',
'PT_CREDITO','PT_FX','PT_RV','PT_SWAPS','REVERFLFL','SLOPE_SABR','STIR_ASIA','STIR_CNH','STIR_EUR',
'STOCKPYME','SWACLIDIV','SWACLIINT','SWAPDIVCO','SWAPDIVNC','SWAPFXIRS','SWAPINTCO','SWAPINTNC',
'SWAPS_CVA','SWAPS_RF','SWAPTION EURO','SWAPTION LARGO','SWAPTION USD','SWAPTIONAV','SWAPTIONUSDBBVA',
'SWBBVA','SWDIRFIN','SWNYBBVA','SW_BANKS','SW_CCY_BASIS','SW_COLAT_PT','SW_CORTO','SW_ELECTRONIC',
'SW_EQUITY','SW_GBP','SW_GERMANY','SW_INSURANCE','SW_PASTORA','SW_TI','SW_TRADING_1','SW_TRADING_2',
'SW_TRADING_3','SW_TRADING_4','SW_TRADING_5','SW_TRADING_6','SW_USD','TAIWAN_FX','TAIWAN_IRS',
'TEMP MC02','TIPDIVCFC','TRD3SPREAD','TWN_LTIRD1_DBU','UNNIM_VTIP','US-INFLATION','UST_BOND','UST_LOCK',
'UST_SPREAD','UST_STRAT','VOL ASSET SWAP','VOL-INFLATION','VOLASIA1','VOLASIA2','VOLASIA3','VOLASIA5',
'VOLASIA6','VOLAUD','VOLCHF','VOLCNY','VOLCNY_EXO','VOLGBP','VOLHKD','VOLHKD_2','VOLJPY','VOLKRW',
'VOLSGD','VOLTWD','VOLUSD','VRMCAPCNF','VRMEXOTIC','VRMEXOTOT','VTABNPVMX','VTACAJAMX','VTC BBVA',
'VTCBDTBBVA','VTCOPCBONOBBVA','VTCSWAPTIONBBVA','VTLBDTBBVA','VTLDIGBBVA','VTLVANILLABBVA','XXBBVLPSW',
'ZZASSETSWAP','ZZMC02','ZZSWAPS','ZZUSA');

select T1.M_NB from TRN_HDR_DBF T1 left join BBVA_FLT_MAP_FULLCORE_DBF T2 on T1.M_NB=T2.M_NB 
where T1.M_TRN_STATUS='LIVE' and (T1.M_BPFOLIO in 
('AAAPDFX1','AAAPDFX2','AAAPDFX3','AAAPDG01','AAAPDG02','AAAPDG04','AAAPDRV1','AAAPDRV2','AAAPDRV3',
'AAAPDTI1','AAAPDTI1B','AAAPDTI2','AAAPDTI3','ANALISTAS','ASSET MILAN','ASSETBONOS','ASSWMIL',
'ASWGOB','BANKING_BOOK','BBV BERMUDA COR','BBV CORTO','BBV CORTO MCO2','BBV DIG','BBV VANILLA',
'BBV VANILLAMC02','BB_ASIA','BCAT TIPOS LARG','BCAT VOL INT','BDT BBV MC02','BDT CORTO MC02',
'BDTBBV2','BDTBBV3','BERM USD COR','BERMUDA DOM','BERMUDA EUROESB','BNACOBLAR','BNACOBVOL','BOND OPT'
,'BOND_INFLATION','BONOS FORWARD','BONOS_LINKERS','CDS_LARGO_PLAZO','CFCHIPOT','CHILENOS',
'CHILENOS BBVA','CL LARGO','CL VOLAT TIPOS','CLOSE BDT BBV','CLOSE BDT MC02','COBERPAT','COBEXTEXO',
'COBMAXMIN','COB_BONOS','COB_EXTERNAL','COB_EXT_TIPOS','CORPOIRS','CORRELACION USD','CORTO NO BDT',
'CORTOPLAZO','CORTO_PLAZO_CLI','CPCDIFWBO','CPCDIOTC','CPCGARENT','CPCVENCOR','CPMDENREG','CPMDERIVA',
'CPMDERMN','CPMDIIRS','CPMDIOTC','CPMSPREMX','CPPI_SWAPS','CRCTASAS','CRDBANCOS','CRDBTBCLP','CRDBTBCOP',
'CRDBTBPEN','CRDCHILE','CRMCHL','CRMPEN','CRMTASAS','CRMTEMPO','CVA_CORTO','CVA_LARGO','CVA_RATES',
'DDIVIRS','DEMESTTC','DEMESTTI','DEMSWAPTI','DEMSWATOT','DEMVOLATI','DEMVOLTOT','DERCOMBI','DIG BBVA',
'DIG DOM','DIG EUROESB','DIGUSDBBVA','ELECTRICAS','ESMCOATRM','ESMDEPOS','ESMDIGTIE','ESMDIGTOT','ESMESTRMI',
'ESMESTRVA','ESMESTTAS','ESMFLEXIC','ESMMMOO','ESMWARRAN','ESP-INFLATION','ESTRATEGIAS','ESTRATFLOW',
'ESTRATGFI','ESTRATGFI_BOND','ETFCORTO','ETFDEUDA','EUR-INFLATION','EUROFIMA','EXOTICAS','FOCSWANEG',
'FOMIRSMNR','FOMMCRO10','FOMMCRO11','FOMMCRO14','FOMMCRO15','FOMMCRO16','FOMMCRO18','FOMMCRO19','FOMMCRO21',
'FOMMCRO22','FOMMCRO25','FOMMCRO29','FOMMICRO2','FOMMICRO4','FOMMICRO5','FOMMICRO8','FOMMICRO9','FOMMIRSNC',
'FOMSWATME','FOMTEMPO','FORWARD','FVA SWAPS','FVA_COLATERAL','FVA_COLAT_BILAT','FVA_COLAT_CCP','FVA_INFLATION',
'FVA_LT_ASIA','FVA_NP_IR','FVA_RATES','FVA_RATES_ASIA','FVA_VOL_RATES','G3','G3_EQUITY','HEDGEAV','HEDGEVIT',
'HIBRIDOS','HIPOTECRED','INDICES DEUDA','INTERNAS_SABR','IRSCOMBI','IRSMEFF','IRSTRAD','IR_CINE','IR_STOCK',
'KOR_LT_SWAP','LARGO NO BDT','LATAM_SWAPS','LIS TIPOS','LON_ESTRUCTURAS','LPMASIGNA','LPMDCCEUR',
'LPMDCCINT','LPMDCCMXN','LPMDCCUSD','LPMDCNCOL','LPMDIDEPO','LPMDIMMOO','LPMDIOTC','LPMDIRBAS','LPMDIRCUR',
'LPMEXDER','LPMIRS1','LPMIRS2','LPMVOLTAS','LPMVOLTOT','LPMXDERSW','LT NY','LT NY2','LT_ASIA','LT_BOND',
'LT_BONDH','LT_BONDT','LT_CNH','LT_HKD','LT_HKFX2','LT_HKFX_CNH','LT_HK_OPT','LT_KOREA','LT_KOREA_REPO',
'LT_KRW','LT_PROGRAM','LT_TWD','MACROBCLSW','MACROBCLVOL','MAD_UST_BTB','MGDSTOXAF','MI ESTRUCTURAS',
'MICROCOB','MKMDERIV','MKMTRDEPO','NON_LIN_HF','NP_COMMODITIES','NP_FOREX','NY_ST_DER','OPCBDTHOJAS',
'OPCION COB','OPCION NC','OPCMIBOR','OPCOTCBON','OPCSALES','OPERPAT','OPTIPCFC','POCXCCY','POMFX',
'POMINVERS','POMIRSTIE','POMUDIMKT','POMUDIS','POMVALREL','POMXCCY','PROFIT','PROJECT_GL_SW','PROJECT_GL_VT',
'PT_CREDITO','PT_FX','PT_RV','PT_SWAPS','REVERFLFL','SLOPE_SABR','STIR_ASIA','STIR_CNH','STIR_EUR',
'STOCKPYME','SWACLIDIV','SWACLIINT','SWAPDIVCO','SWAPDIVNC','SWAPFXIRS','SWAPINTCO','SWAPINTNC',
'SWAPS_CVA','SWAPS_RF','SWAPTION EURO','SWAPTION LARGO','SWAPTION USD','SWAPTIONAV','SWAPTIONUSDBBVA',
'SWBBVA','SWDIRFIN','SWNYBBVA','SW_BANKS','SW_CCY_BASIS','SW_COLAT_PT','SW_CORTO','SW_ELECTRONIC',
'SW_EQUITY','SW_GBP','SW_GERMANY','SW_INSURANCE','SW_PASTORA','SW_TI','SW_TRADING_1','SW_TRADING_2',
'SW_TRADING_3','SW_TRADING_4','SW_TRADING_5','SW_TRADING_6','SW_USD','TAIWAN_FX','TAIWAN_IRS',
'TEMP MC02','TIPDIVCFC','TRD3SPREAD','TWN_LTIRD1_DBU','UNNIM_VTIP','US-INFLATION','UST_BOND','UST_LOCK',
'UST_SPREAD','UST_STRAT','VOL ASSET SWAP','VOL-INFLATION','VOLASIA1','VOLASIA2','VOLASIA3','VOLASIA5',
'VOLASIA6','VOLAUD','VOLCHF','VOLCNY','VOLCNY_EXO','VOLGBP','VOLHKD','VOLHKD_2','VOLJPY','VOLKRW',
'VOLSGD','VOLTWD','VOLUSD','VRMCAPCNF','VRMEXOTIC','VRMEXOTOT','VTABNPVMX','VTACAJAMX','VTC BBVA',
'VTCBDTBBVA','VTCOPCBONOBBVA','VTCSWAPTIONBBVA','VTLBDTBBVA','VTLDIGBBVA','VTLVANILLABBVA','XXBBVLPSW',
'ZZASSETSWAP','ZZMC02','ZZSWAPS','ZZUSA')
or T1.M_SPFOLIO in
('AAAPDFX1','AAAPDFX2','AAAPDFX3','AAAPDG01','AAAPDG02','AAAPDG04','AAAPDRV1','AAAPDRV2','AAAPDRV3',
'AAAPDTI1','AAAPDTI1B','AAAPDTI2','AAAPDTI3','ANALISTAS','ASSET MILAN','ASSETBONOS','ASSWMIL',
'ASWGOB','BANKING_BOOK','BBV BERMUDA COR','BBV CORTO','BBV CORTO MCO2','BBV DIG','BBV VANILLA',
'BBV VANILLAMC02','BB_ASIA','BCAT TIPOS LARG','BCAT VOL INT','BDT BBV MC02','BDT CORTO MC02',
'BDTBBV2','BDTBBV3','BERM USD COR','BERMUDA DOM','BERMUDA EUROESB','BNACOBLAR','BNACOBVOL','BOND OPT'
,'BOND_INFLATION','BONOS FORWARD','BONOS_LINKERS','CDS_LARGO_PLAZO','CFCHIPOT','CHILENOS',
'CHILENOS BBVA','CL LARGO','CL VOLAT TIPOS','CLOSE BDT BBV','CLOSE BDT MC02','COBERPAT','COBEXTEXO',
'COBMAXMIN','COB_BONOS','COB_EXTERNAL','COB_EXT_TIPOS','CORPOIRS','CORRELACION USD','CORTO NO BDT',
'CORTOPLAZO','CORTO_PLAZO_CLI','CPCDIFWBO','CPCDIOTC','CPCGARENT','CPCVENCOR','CPMDENREG','CPMDERIVA',
'CPMDERMN','CPMDIIRS','CPMDIOTC','CPMSPREMX','CPPI_SWAPS','CRCTASAS','CRDBANCOS','CRDBTBCLP','CRDBTBCOP',
'CRDBTBPEN','CRDCHILE','CRMCHL','CRMPEN','CRMTASAS','CRMTEMPO','CVA_CORTO','CVA_LARGO','CVA_RATES',
'DDIVIRS','DEMESTTC','DEMESTTI','DEMSWAPTI','DEMSWATOT','DEMVOLATI','DEMVOLTOT','DERCOMBI','DIG BBVA',
'DIG DOM','DIG EUROESB','DIGUSDBBVA','ELECTRICAS','ESMCOATRM','ESMDEPOS','ESMDIGTIE','ESMDIGTOT','ESMESTRMI',
'ESMESTRVA','ESMESTTAS','ESMFLEXIC','ESMMMOO','ESMWARRAN','ESP-INFLATION','ESTRATEGIAS','ESTRATFLOW',
'ESTRATGFI','ESTRATGFI_BOND','ETFCORTO','ETFDEUDA','EUR-INFLATION','EUROFIMA','EXOTICAS','FOCSWANEG',
'FOMIRSMNR','FOMMCRO10','FOMMCRO11','FOMMCRO14','FOMMCRO15','FOMMCRO16','FOMMCRO18','FOMMCRO19','FOMMCRO21',
'FOMMCRO22','FOMMCRO25','FOMMCRO29','FOMMICRO2','FOMMICRO4','FOMMICRO5','FOMMICRO8','FOMMICRO9','FOMMIRSNC',
'FOMSWATME','FOMTEMPO','FORWARD','FVA SWAPS','FVA_COLATERAL','FVA_COLAT_BILAT','FVA_COLAT_CCP','FVA_INFLATION',
'FVA_LT_ASIA','FVA_NP_IR','FVA_RATES','FVA_RATES_ASIA','FVA_VOL_RATES','G3','G3_EQUITY','HEDGEAV','HEDGEVIT',
'HIBRIDOS','HIPOTECRED','INDICES DEUDA','INTERNAS_SABR','IRSCOMBI','IRSMEFF','IRSTRAD','IR_CINE','IR_STOCK',
'KOR_LT_SWAP','LARGO NO BDT','LATAM_SWAPS','LIS TIPOS','LON_ESTRUCTURAS','LPMASIGNA','LPMDCCEUR',
'LPMDCCINT','LPMDCCMXN','LPMDCCUSD','LPMDCNCOL','LPMDIDEPO','LPMDIMMOO','LPMDIOTC','LPMDIRBAS','LPMDIRCUR',
'LPMEXDER','LPMIRS1','LPMIRS2','LPMVOLTAS','LPMVOLTOT','LPMXDERSW','LT NY','LT NY2','LT_ASIA','LT_BOND',
'LT_BONDH','LT_BONDT','LT_CNH','LT_HKD','LT_HKFX2','LT_HKFX_CNH','LT_HK_OPT','LT_KOREA','LT_KOREA_REPO',
'LT_KRW','LT_PROGRAM','LT_TWD','MACROBCLSW','MACROBCLVOL','MAD_UST_BTB','MGDSTOXAF','MI ESTRUCTURAS',
'MICROCOB','MKMDERIV','MKMTRDEPO','NON_LIN_HF','NP_COMMODITIES','NP_FOREX','NY_ST_DER','OPCBDTHOJAS',
'OPCION COB','OPCION NC','OPCMIBOR','OPCOTCBON','OPCSALES','OPERPAT','OPTIPCFC','POCXCCY','POMFX',
'POMINVERS','POMIRSTIE','POMUDIMKT','POMUDIS','POMVALREL','POMXCCY','PROFIT','PROJECT_GL_SW','PROJECT_GL_VT',
'PT_CREDITO','PT_FX','PT_RV','PT_SWAPS','REVERFLFL','SLOPE_SABR','STIR_ASIA','STIR_CNH','STIR_EUR',
'STOCKPYME','SWACLIDIV','SWACLIINT','SWAPDIVCO','SWAPDIVNC','SWAPFXIRS','SWAPINTCO','SWAPINTNC',
'SWAPS_CVA','SWAPS_RF','SWAPTION EURO','SWAPTION LARGO','SWAPTION USD','SWAPTIONAV','SWAPTIONUSDBBVA',
'SWBBVA','SWDIRFIN','SWNYBBVA','SW_BANKS','SW_CCY_BASIS','SW_COLAT_PT','SW_CORTO','SW_ELECTRONIC',
'SW_EQUITY','SW_GBP','SW_GERMANY','SW_INSURANCE','SW_PASTORA','SW_TI','SW_TRADING_1','SW_TRADING_2',
'SW_TRADING_3','SW_TRADING_4','SW_TRADING_5','SW_TRADING_6','SW_USD','TAIWAN_FX','TAIWAN_IRS',
'TEMP MC02','TIPDIVCFC','TRD3SPREAD','TWN_LTIRD1_DBU','UNNIM_VTIP','US-INFLATION','UST_BOND','UST_LOCK',
'UST_SPREAD','UST_STRAT','VOL ASSET SWAP','VOL-INFLATION','VOLASIA1','VOLASIA2','VOLASIA3','VOLASIA5',
'VOLASIA6','VOLAUD','VOLCHF','VOLCNY','VOLCNY_EXO','VOLGBP','VOLHKD','VOLHKD_2','VOLJPY','VOLKRW',
'VOLSGD','VOLTWD','VOLUSD','VRMCAPCNF','VRMEXOTIC','VRMEXOTOT','VTABNPVMX','VTACAJAMX','VTC BBVA',
'VTCBDTBBVA','VTCOPCBONOBBVA','VTCSWAPTIONBBVA','VTLBDTBBVA','VTLDIGBBVA','VTLVANILLABBVA','XXBBVLPSW',
'ZZASSETSWAP','ZZMC02','ZZSWAPS','ZZUSA')) and T2.M_NB is null;
